
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="w-full h-screen p-4"
      >
        {children}
      </body>
    </html>
  );
}
